#!/bin/bash -e

cd dist

git init
git checkout -b gh-pages
git remote add origin git@github.com:jonathanhunsucker/keyboard.git

git add .

git commit -m "Build on `date`"

git push -f --set-upstream origin gh-pages

rm -rf .git
